name: rtd
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base[version='>=4.2']
  - r-devtools
  - python=3.9
  - pip>=22.3,<=23.2
  - pip:
      - datasets>=2.3.2
      - leidenalg>=0.8.10
      - numba>=0.55.2
      - pandas>=1.3.5
      - scanpy>=1.9.1
      - scvi-tools>=0.16.4
      - scib>=1.0.3
      - torch>=1.13.0
      - torchtext
      - tqdm>=4.64.0
      - typing-extensions>=4.2.0
      - umap-learn>=0.5.3
      - sphinx
      - sphinx_rtd_theme
      - orbax<0.1.8
      - ipykernel
      - nbsphinx
      - nbsphinx-link
      - myst_nb
